[package]
name = "cosmwasm-contract-testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
cosmwasm-std = { version = "1.0.0" }
cosmwasm-storage = { version = "1.0.0" }
cw-storage-plus = { version = "0.13.4", optional = true }
hex = "0.4.3"
rand_chacha = "0.3"
serde = { version = "1", features=["derive"] }
serde_json = "1"
thiserror = "1.0.38"

[features]
default = ["cw-storage-plus"]