[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = "1.0.0"
cosmwasm-contract-testing = { path = "../testing" }
mixnet-contract-common = { path= "../mixnet-contract" }
vesting-contract-common = { path= "../vesting-contract" }
vesting-contract = { path = "../../../contracts/vesting"}
mixnet-contract = { path = "../../../contracts/mixnet"}