[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
cosmwasm-std = "1.0.0"
cw-storage-plus = "0.13.4"
cosmwasm-contract-testing = { path = "../../common/cosmwasm-smart-contracts/testing" }
nym-mixnet-contract-common = { path= "../../common/cosmwasm-smart-contracts/mixnet-contract" }
nym-vesting-contract-common = { path= "../../common/cosmwasm-smart-contracts/vesting-contract" }
nym-vesting-contract = { path = "../vesting"}
nym-mixnet-contract = { path = "../mixnet"}